---
env:
  browser: true
  commonjs: true
  node: true
  es6: true
parser: babel-eslint
extends:
- eslint:recommended
- plugin:react/recommended
plugins:
- react
rules:
  strict:
  - error
  - global
  no-console: 'off'
  no-unused-vars: 1
  react/jsx-no-bind:
  - 1
  - allowArrowFunctions: true
    allowBind: false
    ignoreRefs: true
  react/jsx-key: 1
  react/jsx-pascal-case: 1
  react/jsx-uses-vars: 1
  react/no-did-update-set-state: 1
  react/no-unknown-property: 1
  react/no-unused-prop-types: 1
  react/prop-types: 0
  react/react-in-jsx-scope: 1
  react/no-unescaped-entities: 0
settings:
  react:
    pragma: React
    version: detect
